include:
 - remote: 'https://source.puri.sm/Librem5/librem5-ci/raw/master/librem5-pipeline-definitions.yml'

stages:
 - build
 - test
 - package

.before_script: &before_script
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -y update
    - apt-get -y build-dep .

.image: &image
  image:
    name: debian:bookworm

.tags: &tags
  tags:
    - librem5:arm64

build:native-debian-bookworm:
  <<: *tags
  <<: *image
  <<: *before_script
  artifacts:
    paths:
      - _build
  script:
    - meson --werror _build
    - meson compile -C _build
  except:
    variables:
      - $PKG_ONLY == "1"

package:deb-pureos-byzantium:arm64:
  variables:
    L5_DOCKER_IMAGE: pureos/byzantium
  extends: .l5-build-debian-package
  tags:
    - librem5:arm64
