variables:
  DEPS: meson json-glib-tools

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -y update
  - apt-get -y install $DEPS

.tags: &tags
  tags:
    - librem5

build:native-debian-bullseye:
  <<: *tags
  image: debian:bullseye
  artifacts:
    paths:
      - _build
  script:
    - meson --werror . _build
    - ninja -C _build
