include:
 - remote: 'https://source.puri.sm/Librem5/librem5-ci/raw/master/librem5-pipeline-definitions.yml'

stages:
 - build
 - test
 - package

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -y update
  - apt-get -y build-dep .

.tags: &tags
  tags:
    - librem5

build:native-debian-bullseye:
  <<: *tags
  image: debian:bullseye
  artifacts:
    paths:
      - _build
  script:
    - meson --werror . _build
    - ninja -C _build
  except:
    variables:
      - $PKG_ONLY == "1"

package:deb-pureos-byzantium:arm64:
  variables:
    L5_DOCKER_IMAGE: pureos/byzantium
  extends: .l5-build-debian-package
  tags:
    - librem5:arm64
