---
include:
  - remote: 'https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/6a40df92957c8ce9ee741aaccc5daaaf70545b1e/templates/ci-fairy.yml'
  - remote: 'https://gitlab.gnome.org/guidog/meta-phosh/-/raw/0ed15edd821f8afacbf7a9c0f2a6266873289115/ci/phosh-common-jobs.yml'

variables:
  FDO_UPSTREAM_REPO: agx/feedbackd-device-themes

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Don't trigger a branch pipeline if there is an open MR
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

stages:
 - build
 - test
 - style-checks

.before_script: &before_script
  before_script:
    # Until feedbackd 0.0.2 migrated
    - echo "deb http://deb.debian.org/debian unstable main" >> /etc/apt/sources.list.d/sid.list
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -y update
    - apt-get -y build-dep .

.image: &image
  image:
    name: debian:trixie

build:native-debian-trixie:
  <<: *image
  <<: *before_script
  stage: build
  artifacts:
    paths:
      - _build
  script:
    - meson --werror _build
    - meson compile -C _build
  except:
    variables:
      - $PKG_ONLY == "1"

test:native-debian-trixie:
  <<: *image
  <<: *before_script
  stage: test
  needs:
    - build:native-debian-trixie
  script:
    - meson -Dvalidate=enabled --wipe _build
    - meson test -v --print-errorlogs -C _build
  except:
    variables:
      - $PKG_ONLY == "1"

check-consistency:
  stage: test
  extends: .phosh-check-consistency

check-meson:
  stage: style-checks
  extends:
    - .phosh-check-meson

# Sanity checks of MR settings and commit logs
check-commit-log:
  extends:
    - .fdo.ci-fairy
  stage: style-checks
  variables:
    GIT_DEPTH: "100"
  needs: []
  script: |
    ci-fairy check-commits --signed-off-by --junit-xml=commit-message-junit-report.xml
  artifacts:
    reports:
      junit: commit-message-junit-report.xml
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
