---
include:
  - remote: 'https://gitlab.gnome.org/guidog/meta-phosh/-/raw/0ed15edd821f8afacbf7a9c0f2a6266873289115/ci/phosh-common-jobs.yml'

stages:
 - build
 - test
 - package

.before_script: &before_script
  before_script:
    # Until feedbackd 0.0.2 migrated
    - echo "deb http://deb.debian.org/debian unstable main" >> /etc/apt/sources.list.d/sid.list
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -y update
    - apt-get -y build-dep .

.image: &image
  image:
    name: debian:trixie

.tags: &tags
  tags:
    - librem5:arm64

build:native-debian-trixie:
  <<: *tags
  <<: *image
  <<: *before_script
  stage: build
  artifacts:
    paths:
      - _build
  script:
    - meson --werror _build
    - meson compile -C _build
  except:
    variables:
      - $PKG_ONLY == "1"

test:native-debian-trixie:
  <<: *tags
  <<: *image
  <<: *before_script
  stage: test
  needs:
    - build:native-debian-trixie
  script:
    - meson -Dvalidate=enabled --wipe _build
    - meson test -v --print-errorlogs -C _build
  except:
    variables:
      - $PKG_ONLY == "1"

